[package]
name = "bstvis"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sfml]
path = "/home/dew/projects/github/rust-sfml"
